# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginScreen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginScreen

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod platform :ios, '14.1'

end
